### ISSUE TITLE
List YUV formats supported by the overlay planes in a tranche

### ISSUE THREAD

**Issue by linkmauve** [catacombing/catacomb#150]
On the PinePhone, one plane per CRTC supports YUV formats (here these are planes 0 and 4: https://drmdb.emersion.fr/snapshots/44e1c7995310), but Catacomb currently doesn’t support any of these, making video players like [Livi](https://flathub.org/apps/org.sigxcpu.Livi) crash as they expect to be able to import a NV12 buffer decoded by cedrus into zwp_linux_dmabuf_v1.

The current tranches are: https://linkmauve.fr/files/catacomb-tranches.txt

Livi obviously shouldn’t crash and instead fallback to using the GPU or the CPU for compositing, but this is tracked at https://gitlab.gnome.org/GNOME/gtk/-/issues/6858

**Comment by chrisduerr** [comment]
Seems like master fixed this, likely due to https://github.com/catacombing/catacomb/commit/7605c48f11deb9892a6de993a6fececa668047b3.
