### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by appsforartists** [catacombing/catacomb#154]
Would be nice to have a little blurb for outsiders about what this project is and how active it is.  Is it appropriate for running on your own device, or is it a hobby project just suitable for the maintainers?

**Comment by chrisduerr** [comment]
There is a readme already. Development activity can be best judged by just looking at Github, where it should be obvious that there's frequent updates to components of Catacomb as a whole:

https://github.com/orgs/catacombing/repositories

I run these tools every day, but I can't make that decision for you. If you want to try it and have some questions, I'm happy to answer those.
